/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import Clases.Departamento;
import Clases.Kiosco;
import Clases.Municipio;
import java.awt.Color;
import java.util.ArrayList;
import proyectom.ProyectoM;

/**
 *
 * @author henry
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        this.getContentPane().setBackground(new Color(241,241,241));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Codigok = new javax.swing.JTextField();
        Nombrek = new javax.swing.JTextField();
        CodigoRk = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        listak = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        codreg = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Depa = new javax.swing.JTextField();
        listR = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        listadepss = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        listad = new javax.swing.JComboBox<>();
        munc = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        est = new javax.swing.JTextField();
        esp = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(251, 251, 251));
        jPanel1.setForeground(new java.awt.Color(26, 35, 49));

        jLabel2.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(26, 35, 49));
        jLabel2.setText("Codigo");

        jLabel3.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(26, 35, 49));
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(26, 35, 49));
        jLabel4.setText("Codigo de Region");

        Codigok.setBackground(new java.awt.Color(139, 140, 140));
        Codigok.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        Codigok.setForeground(new java.awt.Color(26, 35, 49));
        Codigok.setBorder(null);

        Nombrek.setBackground(new java.awt.Color(139, 140, 140));
        Nombrek.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        Nombrek.setForeground(new java.awt.Color(26, 35, 49));
        Nombrek.setBorder(null);

        CodigoRk.setBackground(new java.awt.Color(139, 140, 140));
        CodigoRk.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        CodigoRk.setForeground(new java.awt.Color(26, 35, 49));
        CodigoRk.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(26, 35, 49));
        jLabel5.setText("Manejo de Kioscos");

        jButton2.setBackground(new java.awt.Color(209, 48, 71));
        jButton2.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(26, 35, 49));
        jButton2.setText("Ingresar");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        listak.setBackground(new java.awt.Color(139, 140, 140));
        listak.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        listak.setForeground(new java.awt.Color(26, 35, 49));
        listak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listak.setBorder(null);
        listak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listakActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(209, 48, 71));
        jButton3.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(26, 35, 49));
        jButton3.setText("Modificar");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(209, 48, 71));
        jButton4.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(26, 35, 49));
        jButton4.setText("Eliminar");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(listak, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CodigoRk)
                            .addComponent(Nombrek)
                            .addComponent(Codigok)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Codigok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Nombrek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CodigoRk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(listak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Century", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 35, 49));
        jLabel1.setText("Administrador");

        jPanel2.setBackground(new java.awt.Color(251, 251, 251));
        jPanel2.setForeground(new java.awt.Color(26, 35, 49));

        jLabel7.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(26, 35, 49));
        jLabel7.setText("Manejo de departamentos");

        jLabel8.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(26, 35, 49));
        jLabel8.setText("Codigo de Region");

        codreg.setBackground(new java.awt.Color(139, 140, 140));
        codreg.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        codreg.setForeground(new java.awt.Color(26, 35, 49));
        codreg.setBorder(null);

        jLabel9.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(26, 35, 49));
        jLabel9.setText("Region");

        jLabel10.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(26, 35, 49));
        jLabel10.setText("Nombre");

        Depa.setBackground(new java.awt.Color(139, 140, 140));
        Depa.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        Depa.setForeground(new java.awt.Color(26, 35, 49));
        Depa.setBorder(null);

        listR.setBackground(new java.awt.Color(139, 140, 140));
        listR.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        listR.setForeground(new java.awt.Color(26, 35, 49));
        listR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metropolitana", "Norte", "Nororiente", "Suroriente", "Suroccidente", "Noroccidente" }));
        listR.setBorder(null);
        listR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listRActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(209, 48, 71));
        jButton7.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(26, 35, 49));
        jButton7.setText("Ingresar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        listadepss.setBackground(new java.awt.Color(139, 140, 140));
        listadepss.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        listadepss.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listadepss.setBorder(null);
        listadepss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadepssActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(209, 48, 71));
        jButton8.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(26, 35, 49));
        jButton8.setText("Modificar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(209, 48, 71));
        jButton9.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(26, 35, 49));
        jButton9.setText("Eliminar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(26, 35, 49));
        jLabel11.setText("Manejo de municipios");

        jLabel12.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(26, 35, 49));
        jLabel12.setText("Departamento");

        jLabel13.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(26, 35, 49));
        jLabel13.setText("Municipio");

        listad.setBackground(new java.awt.Color(139, 140, 140));
        listad.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        listad.setForeground(new java.awt.Color(26, 35, 49));
        listad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listad.setBorder(null);

        munc.setBackground(new java.awt.Color(139, 140, 140));
        munc.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        munc.setForeground(new java.awt.Color(26, 35, 49));
        munc.setBorder(null);

        jButton10.setBackground(new java.awt.Color(209, 48, 71));
        jButton10.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(26, 35, 49));
        jButton10.setText("Ingresar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(listadepss, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(codreg)
                                    .addComponent(listR, 0, 128, Short.MAX_VALUE)
                                    .addComponent(Depa))
                                .addGap(111, 111, 111)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(listad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(munc)
                                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(152, 152, 152))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(codreg, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(listad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(listR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(munc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jButton10)
                    .addComponent(Depa))
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listadepss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(33, 33, 33))
        );

        jPanel3.setBackground(new java.awt.Color(251, 251, 251));
        jPanel3.setForeground(new java.awt.Color(26, 35, 49));

        jComboBox1.setBackground(new java.awt.Color(139, 140, 140));
        jComboBox1.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(26, 35, 49));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metropolitana", "Norte", "Nororiente", "Suroriente", "Suroccidente", "Noroccidente" }));
        jComboBox1.setBorder(null);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        est.setBackground(new java.awt.Color(139, 140, 140));
        est.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        est.setForeground(new java.awt.Color(26, 35, 49));
        est.setBorder(null);

        esp.setBackground(new java.awt.Color(139, 140, 140));
        esp.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        esp.setForeground(new java.awt.Color(26, 35, 49));
        esp.setBorder(null);
        esp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(209, 48, 71));
        jButton5.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(26, 35, 49));
        jButton5.setText("Modificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(26, 35, 49));
        jLabel6.setText("Manejo de precios de Regiones");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(est, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(esp, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel6)
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(esp)
                        .addComponent(est, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(251, 251, 251));
        jPanel4.setForeground(new java.awt.Color(26, 35, 49));

        jButton6.setBackground(new java.awt.Color(209, 48, 71));
        jButton6.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(26, 35, 49));
        jButton6.setText("Reporte");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(58, 58, 58))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(209, 48, 71));
        jButton1.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(26, 35, 49));
        jButton1.setText("Regresar");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(468, 468, 468)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private String codigk;
    private String nomk;
    private String codigr;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        codigk = Codigok.getText();
        nomk = Nombrek.getText();
        codigr = CodigoRk.getText();
        Kiosco nuevo = new Kiosco(codigk, nomk, codigr);
        ProyectoM.listak.agregarKiosco(nuevo);
        ProyectoM.listak.mostrark();

        listak.removeAllItems();
        ArrayList<Kiosco> listakc = ProyectoM.listak.obtenerListaKioscos();
        for (int i = 0; i < ProyectoM.listak.obtenerListaKioscos().size(); i++) {
            if (listakc.get(i) != null) {
                listak.addItem(listakc.get(i).nombrek);
            }
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void listakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listakActionPerformed
        try {
            int ind = listak.getSelectedIndex();
            String codk = ProyectoM.listak.obtenerKioscos(ind).getCodigok();
            String nomkd = ProyectoM.listak.obtenerKioscos(ind).getNombrek();
            String codR = ProyectoM.listak.obtenerKioscos(ind).getCodigoR();

            CodigoRk.setText(codR);
            Codigok.setText(codk);
            Nombrek.setText(nomkd);

        } catch (Exception ex) {

        }
    }//GEN-LAST:event_listakActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        codigk = Codigok.getText();
        nomk = Nombrek.getText();
        codigr = CodigoRk.getText();
        Kiosco kcs = new Kiosco(codigk, nomk, codigr);
        ProyectoM.listak.modificarKiosco(listak.getSelectedIndex(), kcs);

        listak.removeAllItems();
        ArrayList<Kiosco> listakc = ProyectoM.listak.obtenerListaKioscos();
        for (int i = 0; i < ProyectoM.listak.obtenerListaKioscos().size(); i++) {
            if (listakc.get(i) != null) {
                listak.addItem(listakc.get(i).nombrek);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            int ind = listak.getSelectedIndex();
            ProyectoM.listak.eliminarKiosco(ind);

            listak.removeAllItems();
            ArrayList<Kiosco> listakc = ProyectoM.listak.obtenerListaKioscos();
            for (int i = 0; i < ProyectoM.listak.obtenerListaKioscos().size(); i++) {
                if (listakc.get(i) != null) {
                    listak.addItem(listakc.get(i).nombrek);
                }
            }

        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jButton4ActionPerformed
    int i1 = 0;
    int i2 = 0;
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int indice = jComboBox1.getSelectedIndex();

        switch (indice) {
            case 0:
                i1 = 0;
                i2 = 1;
                break;
            case 1:
                i1 = 2;
                i2 = 3;
                break;
            case 2:
                i1 = 4;
                i2 = 5;
                break;
            case 3:
                i1 = 6;
                i2 = 7;
                break;
            case 4:
                i1 = 8;
                i2 = 9;
                break;
            case 5:
                i1 = 10;
                i2 = 11;
                break;
            default:
                System.out.println("A");
        }
        String precest = Double.toString(ProyectoM.precios.get(i1));
        String precesp = Double.toString(ProyectoM.precios.get(i2));;
        est.setText(precest);
        esp.setText(precesp);


    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        ProyectoM.precios.set(i1, Double.valueOf(est.getText()));
        ProyectoM.precios.set(i2, Double.valueOf(esp.getText()));
    }//GEN-LAST:event_jButton5ActionPerformed
    private String cor;
    private String re;
    private String nd;
    private void listRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listRActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        cor = codreg.getText();
        re = (String) listR.getSelectedItem();
        nd = Depa.getText();
        Departamento dp = new Departamento(cor, re, nd);
        ProyectoM.listadeps.AgregarDep(dp);
        ProyectoM.listadeps.mostrardeps();

        listad.removeAllItems();
        listadepss.removeAllItems();
        ArrayList<Departamento> listaDD = ProyectoM.listadeps.obtenerListaDeps();
        for (int i = 0; i < ProyectoM.listadeps.obtenerListaDeps().size(); i++) {
            if (listaDD.get(i) != null) {
                listad.addItem(listaDD.get(i).dep);
                listadepss.addItem(listaDD.get(i).dep);
            }
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void listadepssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadepssActionPerformed
        try {
int in = listadepss.getSelectedIndex();
String codregion = ProyectoM.listadeps.obtenerDep(in).codr;
String regiond = ProyectoM.listadeps.obtenerDep(in).region;
String depn = ProyectoM.listadeps.obtenerDep(in).dep;
codreg.setText(codregion);
int n=0;
//Metropolitana
//Norte
//Nororiente
//Suroriente
//Suroccidente
//Noroccidente
            if (regiond.equals("Metropolitana")) {
                n = 0;
            }else if(regiond.equals("Norte")){
            n = 1;
            }else if(regiond.equals("Nororiente")){
            n = 2;
            }else if(regiond.equals("Suroriente")){
            n=3;
            }else if(regiond.equals("Suroccidente")){
            n=4;
            }else if(regiond.equals("Noroccidente")){
            n=5;
            }

listR.setSelectedIndex(n);
Depa.setText(depn);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_listadepssActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
          cor = codreg.getText();
        re = (String) listR.getSelectedItem();
        nd = Depa.getText();
        Departamento dp = new Departamento(cor, re, nd);
        ProyectoM.listadeps.modificarDep(listR.getSelectedIndex(), dp);
        
              listad.removeAllItems();
        listadepss.removeAllItems();
        ArrayList<Departamento> listaDD = ProyectoM.listadeps.obtenerListaDeps();
        for (int i = 0; i < ProyectoM.listadeps.obtenerListaDeps().size(); i++) {
            if (listaDD.get(i) != null) {
                listad.addItem(listaDD.get(i).dep);
                listadepss.addItem(listaDD.get(i).dep);
            }
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
      try{
      int indc = listadepss.getSelectedIndex();
      ProyectoM.listadeps.eliminarDep(indc);
              listad.removeAllItems();
        listadepss.removeAllItems();
        ArrayList<Departamento> listaDD = ProyectoM.listadeps.obtenerListaDeps();
        for (int i = 0; i < ProyectoM.listadeps.obtenerListaDeps().size(); i++) {
            if (listaDD.get(i) != null) {
                listad.addItem(listaDD.get(i).dep);
                listadepss.addItem(listaDD.get(i).dep);
            }
        }
      }catch(Exception e){
      
      }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Logeo l = new Logeo();
       l.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
private String Depm;
private String Nmun;
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       Depm = (String) listad.getSelectedItem();
       Nmun = munc.getText();
       Municipio n = new Municipio(Depm,Nmun);
       ProyectoM.listaMC.AgregarMun(n);
       
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    Reporte r = new Reporte();
    r.setVisible(true);
   dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void espActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_espActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodigoRk;
    private javax.swing.JTextField Codigok;
    private javax.swing.JTextField Depa;
    private javax.swing.JTextField Nombrek;
    private javax.swing.JTextField codreg;
    private javax.swing.JTextField esp;
    private javax.swing.JTextField est;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> listR;
    private javax.swing.JComboBox<String> listad;
    private javax.swing.JComboBox<String> listadepss;
    private javax.swing.JComboBox<String> listak;
    private javax.swing.JTextField munc;
    // End of variables declaration//GEN-END:variables
}
