/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import Clases.Departamento;
import Clases.Usuario;
import Clases.Usuarios;
import static Clases.Usuarios.validarPassword;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import proyectom.ProyectoM;

/**
 *
 * @author henry
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.getContentPane().setBackground(new Color(251,251,251));
        nac.removeAllItems();
        ArrayList<Departamento> ld = ProyectoM.listadeps.obtenerListaDeps();
        for (int i = 0; i <ProyectoM.listadeps.obtenerListaDeps().size() ; i++) {
            if (ld.get(i)!=null) {
                nac.addItem(ld.get(i).dep);
            }
        }
        
    }
private String Cor;
private String nom;
private String ape;
private String con;
private String dp;
private String fn;
private String ge;
private String na;
private String us;
private String tl;
private String rl;




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Correo = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Contraseña = new javax.swing.JTextField();
        DPI = new javax.swing.JTextField();
        fecha = new javax.swing.JTextField();
        genero = new javax.swing.JTextField();
        alias = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        rol = new javax.swing.JComboBox<>();
        lista = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        apellido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        nac = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Correo.setBackground(new java.awt.Color(139, 140, 140));
        Correo.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        Correo.setForeground(new java.awt.Color(26, 35, 49));
        Correo.setBorder(null);

        Nombre.setBackground(new java.awt.Color(139, 140, 140));
        Nombre.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        Nombre.setForeground(new java.awt.Color(26, 35, 49));
        Nombre.setBorder(null);

        Contraseña.setBackground(new java.awt.Color(139, 140, 140));
        Contraseña.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        Contraseña.setForeground(new java.awt.Color(26, 35, 49));
        Contraseña.setBorder(null);

        DPI.setBackground(new java.awt.Color(139, 140, 140));
        DPI.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        DPI.setForeground(new java.awt.Color(26, 35, 49));
        DPI.setBorder(null);
        DPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DPIActionPerformed(evt);
            }
        });

        fecha.setBackground(new java.awt.Color(139, 140, 140));
        fecha.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        fecha.setForeground(new java.awt.Color(26, 35, 49));
        fecha.setBorder(null);

        genero.setBackground(new java.awt.Color(139, 140, 140));
        genero.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        genero.setForeground(new java.awt.Color(26, 35, 49));
        genero.setBorder(null);

        alias.setBackground(new java.awt.Color(139, 140, 140));
        alias.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        alias.setForeground(new java.awt.Color(26, 35, 49));
        alias.setBorder(null);

        tel.setBackground(new java.awt.Color(139, 140, 140));
        tel.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        tel.setForeground(new java.awt.Color(26, 35, 49));
        tel.setBorder(null);

        rol.setBackground(new java.awt.Color(139, 140, 140));
        rol.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        rol.setForeground(new java.awt.Color(26, 35, 49));
        rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario Individual", "Usuario Empresarial", "Kiosco" }));
        rol.setBorder(null);
        rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolActionPerformed(evt);
            }
        });

        lista.setBackground(new java.awt.Color(139, 140, 140));
        lista.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        lista.setForeground(new java.awt.Color(26, 35, 49));
        lista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lista de Usuarios" }));
        lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(209, 48, 71));
        jButton1.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(26, 35, 49));
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        apellido.setBackground(new java.awt.Color(139, 140, 140));
        apellido.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        apellido.setForeground(new java.awt.Color(26, 35, 49));
        apellido.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 35, 49));
        jLabel1.setText("Nombre Completo");

        jLabel2.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(26, 35, 49));
        jLabel2.setText("Fecha de Nacimiento");

        jLabel3.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(26, 35, 49));
        jLabel3.setText("Numero de Telefono");

        jLabel4.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(26, 35, 49));
        jLabel4.setText("Correo Electronico");

        jLabel5.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(26, 35, 49));
        jLabel5.setText("DPI");

        jLabel6.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(26, 35, 49));
        jLabel6.setText("Rol");

        jLabel7.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(26, 35, 49));
        jLabel7.setText("Genero");

        jLabel8.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(26, 35, 49));
        jLabel8.setText("Nacionalidad");

        jLabel9.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(26, 35, 49));
        jLabel9.setText("Usuario");

        jLabel10.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(26, 35, 49));
        jLabel10.setText("Contraseña");

        jButton2.setBackground(new java.awt.Color(209, 48, 71));
        jButton2.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(26, 35, 49));
        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(209, 48, 71));
        jButton3.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(26, 35, 49));
        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(209, 48, 71));
        jButton4.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Regresar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        nac.setBackground(new java.awt.Color(139, 140, 140));
        nac.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        nac.setForeground(new java.awt.Color(26, 35, 49));
        nac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Correo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tel))
                                .addGap(70, 70, 70))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(genero)
                                    .addComponent(rol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DPI))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(alias)
                                    .addComponent(Contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nac, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(alias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(DPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(nac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(41, 41, 41)
                .addComponent(jButton4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Cor = Correo.getText();
      nom = Nombre.getText();
      ape = apellido.getText();
      con = Contraseña.getText();
      dp = DPI.getText();
      fn = fecha.getText();
      ge = genero.getText();
      na = (String )nac.getSelectedItem();
      us = alias.getText();
      tl = tel.getText();
      rl = (String) lista.getSelectedItem();
     
      try{
      validarPassword(con);
          System.out.println("Usuario Ingresado Correctamente");
      Usuario user = new Usuario(Cor,nom,ape,con,dp,fn,ge,na,us,tl,rl);
      
      ProyectoM.listaUsarios.agregarUsuario(user);
      ProyectoM.listaUsarios.mostrar();
      JOptionPane.showMessageDialog(null, "El Usuario " + us + " Ha sido agregado Correctamente");
      
      
      }catch(Exception e){
      JOptionPane.showMessageDialog(null, "La contraseña es Incorrecta");
        System.out.println("Contraseña Erronea: " + e.getMessage());
      }
      
      lista.removeAllItems();
      ArrayList<Usuario> listaU = ProyectoM.listaUsarios.obtenerListaUsuarios();
        for (int i = 0; i <ProyectoM.listaUsarios.obtenerListaUsuarios().size(); i++) {
            if (listaU.get(i)!=null) {
                lista.addItem(listaU.get(i).Nombre);
            }
        }
      
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
        
        Cor = Correo.getText();
      nom = Nombre.getText();
      ape = apellido.getText();
      con = Contraseña.getText();
      dp = DPI.getText();
      fn = fecha.getText();
      ge = genero.getText();
      na = (String )nac.getSelectedItem();
      us = alias.getText();
      tl = tel.getText();
      rl = (String) lista.getSelectedItem();
        Usuario user = new Usuario(Cor,nom,ape,con,dp,fn,ge,na,us,tl,rl);
        ProyectoM.listaUsarios.modificarUsuario(lista.getSelectedIndex(), user);
        
           lista.removeAllItems();
      ArrayList<Usuario> listaU = ProyectoM.listaUsarios.obtenerListaUsuarios();
        for (int i = 0; i <ProyectoM.listaUsarios.obtenerListaUsuarios().size(); i++) {
            if (listaU.get(i)!=null) {
                lista.addItem(listaU.get(i).Nombre);
            }
        }
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaActionPerformed
try {
    int index = lista.getSelectedIndex();
    String correo = ProyectoM.listaUsarios.obtenerUsuario(index).getCorreo();
    String nombre = ProyectoM.listaUsarios.obtenerUsuario(index).getNombre();
    String a = ProyectoM.listaUsarios.obtenerUsuario(index).getApe();
    String contra = ProyectoM.listaUsarios.obtenerUsuario(index).getContra();
    String d = ProyectoM.listaUsarios.obtenerUsuario(index).getDPI();
    String fecn = ProyectoM.listaUsarios.obtenerUsuario(index).getFec();
    String gen = ProyectoM.listaUsarios.obtenerUsuario(index).getGen();
    String naci = ProyectoM.listaUsarios.obtenerUsuario(index).getNac();
    String al = ProyectoM.listaUsarios.obtenerUsuario(index).getAlias();
    String t = ProyectoM.listaUsarios.obtenerUsuario(index).getTel();
    String rols = ProyectoM.listaUsarios.obtenerUsuario(index).getRol();
        
    Correo.setText(correo);
    Nombre.setText(nombre);
    apellido.setText(a);
    Contraseña.setText(contra);
    DPI.setText(d);
    fecha.setText(fecn);
    genero.setText(gen);
    
    
    
    
    nac.setSelectedItem(naci);//arreglar para mostrar el correcto
    alias.setText(al);
    tel.setText(t);
    rol.setSelectedItem(rols);
} catch (Exception ex) {
       
}
        
    }//GEN-LAST:event_listaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try{
int indice = lista.getSelectedIndex();
ProyectoM.listaUsarios.eliminarUsuario(indice);
    lista.removeAllItems();
      ArrayList<Usuario> listaU = ProyectoM.listaUsarios.obtenerListaUsuarios();
        for (int i = 0; i <ProyectoM.listaUsarios.obtenerListaUsuarios().size(); i++) {
            if (listaU.get(i)!=null) {
                lista.addItem(listaU.get(i).Nombre);
            }
        }
      
    
}catch (Exception ex){

}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Logeo l = new Logeo();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void DPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DPIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DPIActionPerformed

    private void rolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolActionPerformed
        if (rol.getSelectedItem().equals("Kiosco")) {
            ak a = new ak();
            a.setVisible(true);
        }
      
    }//GEN-LAST:event_rolActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Contraseña;
    private javax.swing.JTextField Correo;
    private javax.swing.JTextField DPI;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField alias;
    private javax.swing.JTextField apellido;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField genero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> lista;
    private javax.swing.JComboBox<String> nac;
    private javax.swing.JComboBox<String> rol;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables
}
