/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import Clases.Compra;
import java.awt.Color;
import java.util.ArrayList;
import proyectom.ProyectoM;

/**
 *
 * @author henry
 */
public class Reporte extends javax.swing.JFrame {

    /**
     * Creates new form Reporte
     */
    public Reporte() {
        initComponents();
        this.getContentPane().setBackground(new Color(251, 251, 251));
        ArrayList<Compra> listaC = ProyectoM.listaCompras.obtenerListaCompra();
        ArrayList<String> nombres = new ArrayList<String>();
        ArrayList<Integer> conteos = new ArrayList<Integer>();

        for (Compra compra : listaC) {
            String nombre = compra.getNomVendedor();
            int indice = nombres.indexOf(nombre);

            if (indice == -1) {
                nombres.add(nombre);
                conteos.add(1);
            } else {
                int contador = conteos.get(indice);
                conteos.set(indice, contador + 1);
            }
        }

        for (int i = 0; i < nombres.size(); i++) {
            String nombre = nombres.get(i);
            int conteo = conteos.get(i);
            String resultado = "El Usuario " + nombre + " Realizo " + conteo + " ventas.\n";
            Reporte.append(resultado);

        }

        ArrayList<String> destinos = new ArrayList<String>();
        ArrayList<Integer> conteosDestinos = new ArrayList<Integer>();

        for (Compra compra : listaC) {
            String destino = compra.getDestino();
            int indice = destinos.indexOf(destino);

            if (indice == -1) {
                destinos.add(destino);
                conteosDestinos.add(1);
            } else {
                int contador = conteosDestinos.get(indice);
                conteosDestinos.set(indice, contador + 1);
            }
        }

        for (int i = 0; i < destinos.size(); i++) {
            String destino = destinos.get(i);
            int conteo = conteosDestinos.get(i);
            String resultado = "El destino " + destino + " tiene " + conteo + " ventas hechas.\n";
            Reporte.append(resultado);
        }

        String resu = "La cantidad de ventas totales es de:  " + destinos.size() + ".\n";
        Reporte.append(resu);

        double sumaTotal = 0.0;

        for (Compra compra : listaC) {
            String totalStr = compra.getTotal();
            double total = Double.parseDouble(totalStr);
            sumaTotal += total;
        }

        String c = "La suma total es: " + sumaTotal;
        Reporte.append(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Reporte = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Reporte.setBackground(new java.awt.Color(139, 140, 140));
        Reporte.setColumns(20);
        Reporte.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        Reporte.setForeground(new java.awt.Color(26, 35, 49));
        Reporte.setRows(5);
        jScrollPane1.setViewportView(Reporte);

        jLabel1.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 35, 49));
        jLabel1.setText("Reporte De Ventas");

        jButton1.setBackground(new java.awt.Color(209, 48, 71));
        jButton1.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(26, 35, 49));
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Admin d = new Admin();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Reporte;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
