/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import Clases.Compra;
import Clases.Cotizacion;
import Clases.DatoF;
import Clases.Departamento;
import Clases.Municipio;
import Clases.Tarjeta;
import Clases.Usuario;
import Clases.chtml;
import java.awt.Desktop;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import proyectom.ProyectoM;

/**
 *
 * @author henry
 */
public class Userr extends javax.swing.JFrame {

    /**
     * Creates new form User
     */
    public Userr() {
        initComponents();
        DepO.removeAllItems();
        DepD.removeAllItems();
        MunO.removeAllItems();
        MunD.removeAllItems();
        ArrayList<Departamento> listaDP = ProyectoM.listadeps.obtenerListaDeps();
        ArrayList<Municipio> listaM = ProyectoM.listaMC.obtenerListaMuns();
        for (int i = 0; i < ProyectoM.listadeps.obtenerListaDeps().size(); i++) {
            if (listaDP.get(i) != null) {
                DepO.addItem(listaDP.get(i).dep);
                DepD.addItem(listaDP.get(i).dep);

            }
        }

        for (int i = 0; i < ProyectoM.listaMC.obtenerListaMuns().size(); i++) {
            if (listaM.get(i) != null) {
                MunO.addItem(listaM.get(i).getNomMun());
                MunD.addItem(listaM.get(i).getNomMun());
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Tarjeta = new javax.swing.JTextField();
        NombreT = new javax.swing.JTextField();
        FecVec = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        NombreDF = new javax.swing.JTextField();
        DireccionDF = new javax.swing.JTextField();
        NitDF = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        ListaDF = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        DepO = new javax.swing.JComboBox<>();
        DepD = new javax.swing.JComboBox<>();
        MunO = new javax.swing.JComboBox<>();
        MunD = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        cantidad = new javax.swing.JTextField();
        peso = new javax.swing.JTextField();
        Totalesp = new javax.swing.JLabel();
        Totalest = new javax.swing.JLabel();
        totales = new javax.swing.JTextField();
        totalet = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        datospc = new javax.swing.JComboBox<>();
        tipopago = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(251, 251, 251));

        Tarjeta.setBackground(new java.awt.Color(139, 140, 140));
        Tarjeta.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        Tarjeta.setForeground(new java.awt.Color(26, 35, 49));
        Tarjeta.setBorder(null);

        NombreT.setBackground(new java.awt.Color(139, 140, 140));
        NombreT.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        NombreT.setForeground(new java.awt.Color(26, 35, 49));
        NombreT.setBorder(null);

        FecVec.setBackground(new java.awt.Color(139, 140, 140));
        FecVec.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        FecVec.setForeground(new java.awt.Color(26, 35, 49));
        FecVec.setBorder(null);

        jButton1.setBackground(new java.awt.Color(209, 48, 71));
        jButton1.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(26, 35, 49));
        jButton1.setText("Ingresar");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(139, 140, 140));
        jTextField1.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(26, 35, 49));
        jTextField1.setText("CVV");
        jTextField1.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(26, 35, 49));
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(26, 35, 49));
        jLabel3.setText("Numero de Tarjeta");

        jLabel4.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(26, 35, 49));
        jLabel4.setText("Fecha de vencimiento");

        jLabel5.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(26, 35, 49));
        jLabel5.setText("Ingreso de Tarjetas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(NombreT)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(FecVec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(Tarjeta, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(115, 115, 115))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FecVec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(209, 48, 71));
        jButton2.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(26, 35, 49));
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(251, 251, 251));

        NombreDF.setBackground(new java.awt.Color(139, 140, 140));
        NombreDF.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        NombreDF.setForeground(new java.awt.Color(26, 35, 49));
        NombreDF.setBorder(null);

        DireccionDF.setBackground(new java.awt.Color(139, 140, 140));
        DireccionDF.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        DireccionDF.setForeground(new java.awt.Color(26, 35, 49));
        DireccionDF.setBorder(null);

        NitDF.setBackground(new java.awt.Color(139, 140, 140));
        NitDF.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        NitDF.setForeground(new java.awt.Color(26, 35, 49));
        NitDF.setBorder(null);

        jButton3.setBackground(new java.awt.Color(209, 48, 71));
        jButton3.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(26, 35, 49));
        jButton3.setText("Ingresar");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(209, 48, 71));
        jButton4.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(26, 35, 49));
        jButton4.setText("Modificar");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(209, 48, 71));
        jButton5.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(26, 35, 49));
        jButton5.setText("Eliminar");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        ListaDF.setBackground(new java.awt.Color(139, 140, 140));
        ListaDF.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        ListaDF.setForeground(new java.awt.Color(26, 35, 49));
        ListaDF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ListaDF.setBorder(null);
        ListaDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaDFActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(26, 35, 49));
        jLabel6.setText("Ingreso de Datos de Facturacion");

        jLabel7.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(26, 35, 49));
        jLabel7.setText("Nombre");

        jLabel8.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(26, 35, 49));
        jLabel8.setText("Direccion");

        jLabel9.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(26, 35, 49));
        jLabel9.setText("Nit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ListaDF, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(88, 88, 88))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NitDF, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DireccionDF, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreDF, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DireccionDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NitDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListaDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(251, 251, 251));

        DepO.setBackground(new java.awt.Color(139, 140, 140));
        DepO.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        DepO.setForeground(new java.awt.Color(26, 35, 49));
        DepO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DepO.setBorder(null);

        DepD.setBackground(new java.awt.Color(139, 140, 140));
        DepD.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        DepD.setForeground(new java.awt.Color(26, 35, 49));
        DepD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DepD.setBorder(null);

        MunO.setBackground(new java.awt.Color(139, 140, 140));
        MunO.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        MunO.setForeground(new java.awt.Color(26, 35, 49));
        MunO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        MunO.setBorder(null);

        MunD.setBackground(new java.awt.Color(139, 140, 140));
        MunD.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        MunD.setForeground(new java.awt.Color(26, 35, 49));
        MunD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        MunD.setBorder(null);

        jButton6.setBackground(new java.awt.Color(209, 48, 71));
        jButton6.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(26, 35, 49));
        jButton6.setText("Calcular");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        cantidad.setBackground(new java.awt.Color(139, 140, 140));
        cantidad.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        cantidad.setForeground(new java.awt.Color(26, 35, 49));
        cantidad.setBorder(null);

        peso.setBackground(new java.awt.Color(139, 140, 140));
        peso.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        peso.setForeground(new java.awt.Color(26, 35, 49));
        peso.setBorder(null);

        Totalesp.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        Totalesp.setForeground(new java.awt.Color(26, 35, 49));
        Totalesp.setText("Total Especial");

        Totalest.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        Totalest.setForeground(new java.awt.Color(26, 35, 49));
        Totalest.setText("Total Estandar");

        totales.setBackground(new java.awt.Color(139, 140, 140));
        totales.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        totales.setForeground(new java.awt.Color(26, 35, 49));
        totales.setBorder(null);

        totalet.setBackground(new java.awt.Color(139, 140, 140));
        totalet.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        totalet.setForeground(new java.awt.Color(26, 35, 49));
        totalet.setBorder(null);

        jButton7.setBackground(new java.awt.Color(209, 48, 71));
        jButton7.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(26, 35, 49));
        jButton7.setText("Elegir");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(209, 48, 71));
        jButton8.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(26, 35, 49));
        jButton8.setText("Elegir");
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(26, 35, 49));
        jLabel10.setText("Cotizacion de Productos");

        jLabel11.setFont(new java.awt.Font("Source Sans Pro Black", 0, 18)); // NOI18N
        jLabel11.setText("→");

        jLabel12.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(26, 35, 49));
        jLabel12.setText("Cantidad de Paquetes a enviar");

        jLabel13.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(26, 35, 49));
        jLabel13.setText("Peso de Paquetes");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DepO, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MunO, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                    .addComponent(peso)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(MunD, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DepD, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Totalest)
                            .addComponent(Totalesp))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalet)
                            .addComponent(totales, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DepO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(DepD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MunO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MunD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Totalest)
                    .addComponent(totalet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Totalesp)
                    .addComponent(totales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(251, 251, 251));

        datospc.setBackground(new java.awt.Color(139, 140, 140));
        datospc.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        datospc.setForeground(new java.awt.Color(26, 35, 49));
        datospc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        datospc.setBorder(null);
        datospc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datospcActionPerformed(evt);
            }
        });

        tipopago.setBackground(new java.awt.Color(139, 140, 140));
        tipopago.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        tipopago.setForeground(new java.awt.Color(26, 35, 49));
        tipopago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pago Contra Entrega", "Pago con Tarjeta" }));
        tipopago.setBorder(null);
        tipopago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipopagoActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(209, 48, 71));
        jButton9.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(26, 35, 49));
        jButton9.setText("Comprar");
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(209, 48, 71));
        jButton10.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(26, 35, 49));
        jButton10.setText("Ver envios Solicitados");
        jButton10.setBorder(null);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(26, 35, 49));
        jLabel14.setText("Tipo de Pago");

        jLabel15.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(26, 35, 49));
        jLabel15.setText("Datos de Facturacion");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datospc, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipopago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipopago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datospc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private String trj;
    private String nmb;
    private String fv;
    private String nmbf = ProyectoM.listaUsarios.obtenerUsuario(0).Alias;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        trj = Tarjeta.getText();
        nmb = NombreT.getText();
        fv = FecVec.getText();

        Tarjeta t = new Tarjeta(trj, nmb, fv);
        ProyectoM.listaTarjetas.AgregarTarjeta(t);
        ProyectoM.listaTarjetas.mostrarT();
//        String S = ProyectoM.listaUsarios.UserL(); Este dato seria el Usuario logeado en este momento, utilizar este dato para ingresar en un arraylist
//        System.out.println(S);                     y hacer el ordenamiento de cantidad de ventas por usuario
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Logeo f = new Logeo();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    private String nomf;
    private String direcf;
    private String nit;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        nomf = NombreDF.getText();
        direcf = DireccionDF.getText();
        nit = NitDF.getText();
        DatoF ld = new DatoF(nomf, direcf, nit);
        ProyectoM.listadatos.AgregarDatosF(ld);
        ProyectoM.listadatos.mostrarDatosF();

        ListaDF.removeAllItems();
        datospc.removeAllItems();
        ArrayList<DatoF> listaDfs = ProyectoM.listadatos.obtenerListaDatosF();
        for (int i = 0; i < ProyectoM.listadatos.obtenerListaDatosF().size(); i++) {
            if (listaDfs.get(i) != null) {
                ListaDF.addItem(listaDfs.get(i).getNomF());
                datospc.addItem(listaDfs.get(i).getNomF());
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ListaDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaDFActionPerformed

        try {
            int indice = ListaDF.getSelectedIndex();
            String n = ProyectoM.listadatos.obtenerDatosF(indice).getNomF();
            String d = ProyectoM.listadatos.obtenerDatosF(indice).GetDirecF();
            String ni = ProyectoM.listadatos.obtenerDatosF(indice).getNitF();

            NombreDF.setText(n);
            DireccionDF.setText(d);
            NitDF.setText(ni);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_ListaDFActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        nomf = NombreDF.getText();
        direcf = DireccionDF.getText();
        nit = NitDF.getText();
        DatoF ld = new DatoF(nomf, direcf, nit);
        ProyectoM.listadatos.modifcarDatosF(ListaDF.getSelectedIndex(), ld);

        ListaDF.removeAllItems();
        ArrayList<DatoF> listaDfs = ProyectoM.listadatos.obtenerListaDatosF();
        for (int i = 0; i < ProyectoM.listadatos.obtenerListaDatosF().size(); i++) {
            if (listaDfs.get(i) != null) {
                ListaDF.addItem(listaDfs.get(i).getNomF());
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        try {
            int indice = ListaDF.getSelectedIndex();
            ProyectoM.listadatos.EliminarDatosF(indice);
            ListaDF.removeAllItems();
            ArrayList<DatoF> listaDfs = ProyectoM.listadatos.obtenerListaDatosF();
            for (int i = 0; i < ProyectoM.listadatos.obtenerListaDatosF().size(); i++) {
                if (listaDfs.get(i) != null) {
                    ListaDF.addItem(listaDfs.get(i).getNomF());
                }
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton5ActionPerformed
    private String prec;
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int ind = DepD.getSelectedIndex();
        String RegionEnvio = ProyectoM.listadeps.obtenerDep(ind).region;
        int i1 = 0;
        int i2 = 0;
        if (RegionEnvio.equals("Metropolitana")) {
            i1 = 0;
            i2 = 1;
        } else if (RegionEnvio.equals("Norte")) {
            i1 = 2;
            i2 = 3;
        } else if (RegionEnvio.equals("Nororiente")) {
            i1 = 4;
            i2 = 5;
        } else if (RegionEnvio.equals("Suroriente")) {
            i1 = 6;
            i2 = 7;
        } else if (RegionEnvio.equals("Suroccidente")) {
            i1 = 8;
            i2 = 9;
        } else if (RegionEnvio.equals("Noroccidente")) {
            i1 = 10;
            i2 = 11;
        }
        Double precesp = ProyectoM.precios.get(i1);
        Double precest = ProyectoM.precios.get(i2);
        Double c = Double.valueOf(cantidad.getText());
        Double p = Double.valueOf(peso.getText());
        Double TotalEspp = precesp * c * p;
        Double TotalEst = precest * c * p;

        totales.setText(Double.toString(TotalEspp));
        totalet.setText(Double.toString(TotalEst));


    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String S = ProyectoM.listaUsarios.UserL();
        Cotizacion cn = new Cotizacion(S, (String) DepO.getSelectedItem(), (String) MunO.getSelectedItem(), (String) DepD.getSelectedItem(), (String) MunD.getSelectedItem(), Integer.parseInt(cantidad.getText()), peso.getText(), totales.getText());
        ProyectoM.listaCot.AgregarCot(cn);
        ProyectoM.listaCot.mostrarCot();
        prec = (String) totales.getText();
        String htm = "Producto con origen en: " + (String) DepO.getSelectedItem() + "\n"
                + "Producto con destino a: " + (String) DepD.getSelectedItem() + "\n"
                + "Tiene un precio de: " + totales.getText();

        ProyectoM.html.setContenido(htm);
        ProyectoM.html.crearArchivo();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String S = ProyectoM.listaUsarios.UserL();
        Cotizacion cn = new Cotizacion(S, (String) DepO.getSelectedItem(), (String) MunO.getSelectedItem(), (String) DepD.getSelectedItem(), (String) MunD.getSelectedItem(), Integer.parseInt(cantidad.getText()), peso.getText(), totalet.getText());
        ProyectoM.listaCot.AgregarCot(cn);
        ProyectoM.listaCot.mostrarCot();
        prec = (String) totalet.getText();

        String htmd = "Producto con origen en: " + (String) DepO.getSelectedItem() + "\n"
                + "Producto con destino a: " + (String) DepD.getSelectedItem() + "\n"
                + "Tiene un precio de: " + totales.getText();

        ProyectoM.html.setContenido(htmd);
        ProyectoM.html.crearArchivo();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void datospcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datospcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datospcActionPerformed
    private int numf = 0;
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        numf++;
        Random random = new Random();
        String cod = "IPC1B";
        String codg = "";
        String Codf;

        for (int i = 0; i < 5; i++) {
            char randomizedCharacter = (char) (random.nextInt(26) + 'a');
            codg = codg + randomizedCharacter;
        }
        Codf = cod + codg;// codigo factura

        String a = ProyectoM.listaUsarios.UserL();//
        int b = numf;
        String c = (String) DepO.getSelectedItem();//
        String d = (String) DepD.getSelectedItem();//
        int ie = datospc.getSelectedIndex();
        String e = ProyectoM.listadatos.obtenerDatosF(ie).getNitF();//
        String f = (String) tipopago.getSelectedItem();//
        String g = peso.getText();//
        String h = cantidad.getText();//
        
        if (tipopago.getSelectedIndex()==0) {
            prec = prec + 5;
        }
        String i = prec;
        Compra l = new Compra(b, Codf, c, d, e, f, g, h, a, i);
        ProyectoM.listaCompras.AgregarCompra(l);
        ProyectoM.listaCompras.mostrarCompras();
        String CompraH = "Numero de factura: " + b + "\n"
                + "Etiqueta de envio: " + Codf + "\n"
                + "Origen en:" + c + "  Destino en:" + d + "\n"
                + "Nit: " + e + "\n"
                + "Tipo de Pago: " + f + "\n"
                + "Peso Producto: " + g + "\n"
                + "Cantidad de Paquetes a enviar" + h + "\n"
                + "Usuario: " + a + "\n"
                + "Precio Total del Envio:  " + i;
 Date date = new Date();
            String guiaH = 
                 "Codigo de Paquete: " + Codf + "\n"
                + "Origen en:" + c + "  Destino en:" + d + "\n"
                + "Tipo de Pago: " + f + "\n"
                + "Peso Producto: " + g + "\n"
                + "Cantidad de Paquetes a enviar" + h + "\n"
                + date+ "\n"
                + "Precio Total del Envio:  " + i;
            ProyectoM.ghtml.setContenido(guiaH);
            ProyectoM.ghtml.crearArchivo();
        
        ProyectoM.fhtml.setContenido(CompraH);
        ProyectoM.fhtml.crearArchivo();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
 try {
                // Especificar la ruta del archivo a abrir
                File file = new File("C:\\Users\\henry\\OneDrive\\Escritorio\\Proyecto1\\factura.html");
                File file1 = new File("C:\\Users\\henry\\OneDrive\\Escritorio\\Proyecto1\\Guia.html");

                // Abrir el archivo con el programa predeterminado
                Desktop.getDesktop().open(file);
                Desktop.getDesktop().open(file1);
            } catch (Exception e) {
               
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void tipopagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipopagoActionPerformed
        if (tipopago.getSelectedIndex()==1) {
            Tarjetasl t = new Tarjetasl();
            t.setVisible(true);
        }
    }//GEN-LAST:event_tipopagoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DepD;
    private javax.swing.JComboBox<String> DepO;
    private javax.swing.JTextField DireccionDF;
    private javax.swing.JTextField FecVec;
    private javax.swing.JComboBox<String> ListaDF;
    private javax.swing.JComboBox<String> MunD;
    private javax.swing.JComboBox<String> MunO;
    private javax.swing.JTextField NitDF;
    private javax.swing.JTextField NombreDF;
    private javax.swing.JTextField NombreT;
    private javax.swing.JTextField Tarjeta;
    private javax.swing.JLabel Totalesp;
    private javax.swing.JLabel Totalest;
    private javax.swing.JTextField cantidad;
    private javax.swing.JComboBox<String> datospc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField peso;
    private javax.swing.JComboBox<String> tipopago;
    private javax.swing.JTextField totales;
    private javax.swing.JTextField totalet;
    // End of variables declaration//GEN-END:variables
}
